### ISSUE TITLE
wu go build 

### ISSUE THREAD

**Issue by liyu4** [shanzi/wu#2]
2016/08/29 19:46:22 [E] Failed to open config file:  open .wu.json: no such file or directory
2016/08/29 19:46:22 [I] Start watching...
2016/08/29 19:46:22 [I] - Runing command: go build
2016/08/29 19:46:25 [I] - Done.
2016/08/29 19:46:25 [I] File changed: /Users/admin/svn/src/monitor/monitor
2016/08/29 19:46:25 [I] - Runing command: go build
2016/08/29 19:46:27 [I] - Done.
2016/08/29 19:46:28 [I] File changed: /Users/admin/svn/src/monitor/monitor
2016/08/29 19:46:28 [I] - Runing command: go build
2016/08/29 19:46:30 [I] - Done.
2016/08/29 19:46:30 [I] File changed: /Users/admin/svn/src/monitor/monitor
2016/08/29 19:46:30 [I] - Runing command: go build
2016/08/29 19:46:32 [I] - Done.
2016/08/29 19:46:33 [I] File changed: /Users/admin/svn/src/monitor/monitor
2016/08/29 19:46:33 [I] - Runing command: go build
2016/08/29 19:46:35 [I] - Done.
^C2016/08/29 19:46:35 [I] Shutting down...
2016/08/29 19:46:35 [I] File changed: /Users/admin/svn/src/monitor/monitor
2016/08/29 19:46:35 [I] - Runing command: go build

command line: wu go build 
wu 在一个项目内部的话，会循环监视到文件的改变，效果如上

**Comment by shanzi** [comment]
@liyu4 go build 本身会在当前文件目录下覆盖编译出来的 Executable，那么自然会产生循环。您可以使用 `wu -pattern='*.go' go build` 让它只过滤出 go 文件。或者使用 go install 来编译。

**Comment by liyu4** [comment]
@shanzi 是的，配置文件本身就是带了*.go , 这里因为没有解析到配置文件、所以要自己指定模式，go install 是将文件写到bin目录下，自然就可以避免🐶 build产生的问题。

**Comment by shanzi** [comment]
@liyu4 所以应该是没有问题的吧？

**Comment by liyu4** [comment]
@shanzi 可能有点跑题了，但是配置文件很容易解析不到。比如你要监控另外一个项目。

**Comment by shanzi** [comment]
@liyu4 也许可以做一个全局的config，但是因为不同项目可能会需要不同的配置，所以其实还是建议每个项目都有自己的config，用`wu -save`应该能很方便的生成。
